
-- Update existing NRRO users with their correct first_name and last_name
UPDATE public.users SET first_name = v.first_name, last_name = v.last_name
FROM (VALUES
  ('a.montero@nrro.es', 'Adrián', 'Montero'),
  ('a.munoz@nrro.es', 'Adrián', 'Muñoz'),
  ('a.virto@nrro.es', 'Alba', 'Virto'),
  ('a.vicente@nrro.es', 'Alberto', 'Vicente'),
  ('a.miro@nrro.es', 'Aleix', 'Miró'),
  ('a.brotons@nrro.es', 'Alejandro', 'Brotons'),
  ('a.ramirez@nrro.es', 'Ana', 'Ramírez'),
  ('a.raso@nrro.es', 'Anabel', 'Raso'),
  ('a.martin@nrro.es', 'Angelo', 'Martín'),
  ('b.salvo@nrro.es', 'Blanca', 'Salvó'),
  ('c.sacco@nrro.es', 'Carolina', 'Sacco'),
  ('cp.sanchez@nrro.es', 'Cinthia Paola', 'Sánchez'),
  ('c.bellonch@nrro.es', 'Clara', 'Bellonch'),
  ('c.gimenez@nrro.es', 'Clara', 'Giménez'),
  ('c.martin@nrro.es', 'Claudia', 'Martín'),
  ('d.gomez@nrro.es', 'David', 'Gómez Rovira'),
  ('e.abellan@nrro.es', 'Eric', 'Abellán'),
  ('e.borrell@nrro.es', 'Estel', 'Borrell'),
  ('g.zalacain@nrro.es', 'Gemma', 'Zalacain'),
  ('g.iriarte@nrro.es', 'Gerard', 'Iriarte'),
  ('i.velarde@nrro.es', 'Irene', 'Velarde'),
  ('I.Rodriguez@nrro.es', 'Iván', 'Rodríguez Ruiz'),
  ('j.salvo@nrro.es', 'Joan', 'Salvó'),
  ('j.majoral@nrro.es', 'Jordi', 'Majoral'),
  ('j.bonet@nrro.es', 'Jose', 'Bonet'),
  ('jm.arguello@nrro.es', 'José María', 'Argüello'),
  ('jl.dambrosio@nrro.es', 'Juan Luis', 'Dambrosio'),
  ('j.estelle@nrro.es', 'Júlia', 'Estellé'),
  ('l.moll@nrro.es', 'Laia', 'Moll'),
  ('ll.montanya@nrro.es', 'Lluís', 'Montanya'),
  ('L.linares@nrro.es', 'Lucia', 'Linares'),
  ('m.vidueira@nrro.es', 'Magdalena', 'Vidueira'),
  ('m.canet@nrro.es', 'Marc', 'Canet'),
  ('m.leon@nrro.es', 'María', 'León'),
  ('m.ventin@nrro.es', 'María', 'Ventín'),
  ('m.fernandez@nrro.es', 'Mía', 'Fernández'),
  ('m.castro@nrro.es', 'Mónica', 'Castro'),
  ('n.moreno@nrro.es', 'Nil', 'Moreno'),
  ('o.moron@nrro.es', 'Oriol', 'Morón'),
  ('p.valls@nrro.es', 'Pau', 'Valls'),
  ('p.cardenas@nrro.es', 'Paula', 'Cárdenas'),
  ('p.rico@nrro.es', 'Pepe', 'Rico'),
  ('p.dambrosio@nrro.es', 'Pilar', 'D''Ambrosio'),
  ('p.fontclara@nrro.es', 'Pol', 'Fontclara'),
  ('q.vall@nrro.es', 'Queralt', 'Vall'),
  ('r.chica@nrro.es', 'Raquel', 'Chica'),
  ('r.rubio@nrro.es', 'Raul', 'Rubio'),
  ('r.serra@nrro.es', 'Roc', 'Serra'),
  ('r.rodriguez@nrro.es', 'Rosa', 'Rodríguez'),
  ('s.alonso@nrro.es', 'Sara', 'Alonso'),
  ('s.sanz@nrro.es', 'Sara', 'Sanz'),
  ('v.lenko@nrro.es', 'Vasyl', 'Lenko'),
  ('y.aguilera@nrro.es', 'Yasmina', 'Aguilera'),
  ('y.pescador@nrro.es', 'Yolanda', 'Pescador'),
  ('y.huang@nrro.es', 'Yuxiang', 'Huang')
) AS v(email, first_name, last_name)
WHERE lower(public.users.email) = lower(v.email);
